/*
 * Copyright (C) 2026 Nick Edson
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * GPL-3.0-or-later any later version.
 */

// =======================================================================
//  GENERATED FILE - do not edit by hand.
//
//  S.M.A.R.T. attribute name tables extracted verbatim from
//  CrystalDiskInfo  <https://github.com/hiyohiyo/CrystalDiskInfo>
//  Language/English.lang  ([Smart*] sections), MIT License.
// =======================================================================

#include "CdiAttributeName.h"

#include <cstring>

// CdiAttributeName.h declares CdiAttrName / CdiAttrTable / CdiFindAttrTable
// inside namespace cdi, so the tables have to live there too.  The extractor
// that produced this file emits them at global scope; the wrapper below is
// the only hand edit, and re-running the extractor means re-applying it.
namespace cdi {

static const CdiAttrName kSmart[] = {
    { 0x01, "Read Error Rate" },
    { 0x02, "Throughput Performance" },
    { 0x03, "Spin-Up Time" },
    { 0x04, "Start/Stop Count" },
    { 0x05, "Reallocated Sectors Count" },
    { 0x06, "Read Channel Margin" },
    { 0x07, "Seek Error Rate" },
    { 0x08, "Seek Time Performance" },
    { 0x09, "Power-On Hours" },
    { 0x0A, "Spin Retry Count" },
    { 0x0B, "Recalibration Retries" },
    { 0x0C, "Power Cycle Count" },
    { 0x0D, "Soft Read Error Rate stab" },
    { 0x16, "Current Helium Level" },
    { 0xB8, "End-to-End Error" },
    { 0xBB, "Reported Uncorrectable Errors" },
    { 0xBC, "Command Timeout" },
    { 0xBD, "High Fly Writes" },
    { 0xBE, "Airflow Temperature" },
    { 0xBF, "G-Sense Error Rate" },
    { 0xC0, "Power-off Retract Count" },
    { 0xC1, "Load/Unload Cycle Count" },
    { 0xC2, "Temperature" },
    { 0xC3, "Hardware ECC recovered" },
    { 0xC4, "Reallocation Event Count" },
    { 0xC5, "Current Pending Sector Count" },
    { 0xC6, "Uncorrectable Sector Count" },
    { 0xC7, "UltraDMA CRC Error Count" },
    { 0xC8, "Write Error Rate" },
    { 0xC9, "Soft Read Error Rate" },
    { 0xCA, "Data Address Mark Error" },
    { 0xCB, "Run Out Cancel" },
    { 0xCC, "Soft ECC Correction" },
    { 0xCD, "Thermal Asperity Rate" },
    { 0xCE, "Flying Height" },
    { 0xCF, "Spin High Current" },
    { 0xD0, "Spin Buzz" },
    { 0xD1, "Offline Seek Performance" },
    { 0xD3, "Vibration During Write" },
    { 0xD4, "Shock During Write" },
    { 0xDC, "Disk Shift" },
    { 0xDD, "G-Sense Error Rate" },
    { 0xDE, "Loaded Hours" },
    { 0xDF, "Load/Unload Retry Count" },
    { 0xE0, "Load Friction" },
    { 0xE1, "Load/Unload Cycle Count" },
    { 0xE2, "Load 'In'-time" },
    { 0xE3, "Torque Amplification Count" },
    { 0xE4, "Power-Off Retract Cycle" },
    { 0xE6, "GMR Head Amplitude" },
    { 0xE7, "Temperature" },
    { 0xF0, "Head Flying Hours" },
    { 0xFA, "Read Error Retry Rate" },
    { 0xFE, "Free Fall Protection" },
    { 0xF1, "Total Host Writes" },
    { 0xF2, "Total Host Reads" },
    { 0x17, "Helium Condition Lower" },
    { 0x18, "Helium Condition Upper" },
    { 0x1B, "MAMR Health Monitor" },
};

static const CdiAttrName kSmartSsd[] = {
    { 0x01, "Read Error Rate" },
    { 0x02, "Throughput Performance" },
    { 0x03, "Spin-Up Time" },
    { 0x04, "Start/Stop Count" },
    { 0x05, "Reallocated Sectors Count" },
    { 0x06, "Read Channel Margin" },
    { 0x07, "Seek Error Rate" },
    { 0x08, "Seek Time Performance" },
    { 0x09, "Power-On Hours" },
    { 0x0A, "Spin Retry Count" },
    { 0x0B, "Recalibration Retries" },
    { 0x0C, "Power Cycle Count" },
    { 0x0D, "Soft Read Error Rate stab" },
    { 0xC0, "Unsafe Shutdown Count" },
    { 0xC2, "Temperature" },
    { 0xC4, "Reallocation Event Count" },
    { 0xC5, "Current Pending Sector Count" },
    { 0xC6, "Uncorrectable Sector Count" },
    { 0xFF, "Remaining Life" },
    { 0xF1, "Total Host Writes" },
    { 0xF2, "Total Host Reads" },
};

static const CdiAttrName kSmartMtron[] = {
    { 0xBB, "Total Erase Count" },
};

static const CdiAttrName kSmartIndilinx[] = {
    { 0x01, "Read Error Rate" },
    { 0x09, "Power-On Hours" },
    { 0x0C, "Power Cycle Count" },
    { 0xB8, "Initial Bad Block Count" },
    { 0xC2, "Temperature" },
    { 0xC3, "Program Failure Block Count" },
    { 0xC4, "Erase Failure Block Count" },
    { 0xC5, "Read Failure Block Count" },
    { 0xC6, "Total Count of Read Sectors" },
    { 0xC7, "Total Count of Write Sectors" },
    { 0xC8, "Total Count of Read Commands" },
    { 0xC9, "Total Count of Write Commands" },
    { 0xCA, "Total Count of Error bits from flash" },
    { 0xCB, "Total Count of Read Sectors with Correctable Bit Errors" },
    { 0xCC, "Bad Block Full Flag" },
    { 0xCD, "Maximum PE Count Specification" },
    { 0xCE, "Minimum Erase Count" },
    { 0xCF, "Maximum Erase Count" },
    { 0xD0, "Average Erase Count" },
    { 0xD1, "Remaining Drive Life" },
};

static const CdiAttrName kSmartJMicron60x[] = {
    { 0x09, "Power-On Hours" },
    { 0x0C, "Power Cycle Count" },
    { 0xC2, "Temperature" },
    { 0xE5, "Halt System ID, Flash ID" },
    { 0xE8, "Firmware Version Information" },
    { 0xE9, "ECC Fail Record" },
    { 0xEA, "Average Erase Count, Max Erase Count" },
    { 0xEB, "Good Block Count, System Block Count" },
};

static const CdiAttrName kSmartIntel[] = {
    { 0x03, "Spin Up Time" },
    { 0x04, "Start/Stop Count" },
    { 0x05, "Re-Allocated Sector Count" },
    { 0x09, "Power-On Hours Count" },
    { 0x0C, "Power Cycle Count" },
    { 0xAA, "Available Reserved Space" },
    { 0xAB, "Program Fail Count" },
    { 0xAC, "Erase Fail Count" },
    { 0xAE, "Unexpected Power Loss" },
    { 0xAF, "Power Loss Protection Failure" },
    { 0xB7, "SATA Downshift Count" },
    { 0xB8, "End to End Error Detection Count" },
    { 0xBB, "Uncorrectable Error Count" },
    { 0xBE, "Temperature" },
    { 0xC0, "Unsafe Shutdown Count" },
    { 0xC2, "Temperature" },
    { 0xC5, "Pending Sector Count" },
    { 0xC7, "CRC Error Count" },
    { 0xE1, "Host Writes" },
    { 0xE2, "Timed Workload Media Wear" },
    { 0xE3, "Timed Workload Host Read/Write Ratio" },
    { 0xE4, "Timed Workload Timer" },
    { 0xE8, "Available Reserved Space" },
    { 0xE9, "Media Wearout Indicator" },
    { 0xEA, "Thermal Throttle Status" },
    { 0xF1, "Total LBAs Written" },
    { 0xF2, "Total LBAs Read" },
    { 0xF3, "Total NAND Writes" },
    { 0xF9, "Total NAND Writes" },
};

static const CdiAttrName kSmartSamsung[] = {
    { 0x05, "Reallocated Sector Count" },
    { 0x09, "Power-on Hours" },
    { 0x0C, "Power-on Count" },
    { 0xAF, "Program Fail Count (Chip)" },
    { 0xB0, "Erase Fail Count (Chip)" },
    { 0xB1, "Wear Leveling Count" },
    { 0xB2, "Used Reserved Block Count (Chip)" },
    { 0xB3, "Used Reserved Block Count (Total)" },
    { 0xB4, "Unused Reserved Block Count (Total)" },
    { 0xB5, "Program Fail Count (Total)" },
    { 0xB6, "Erase Fail Count (Total)" },
    { 0xB7, "Runtime Bad Block (Total)" },
    { 0xBB, "Uncorrectable Error Count" },
    { 0xBE, "Airflow Temperature" },
    { 0xC2, "Temperature" },
    { 0xC3, "ECC Error Rate" },
    { 0xC6, "Off-Line Uncorrectable Error Count" },
    { 0xC7, "CRC Error Count" },
    { 0xC9, "Super cap Status" },
    { 0xCA, "SSD Mode Status" },
    { 0xEB, "POR Recovery Count" },
    { 0xF1, "Total LBAs Written" },
    { 0xF2, "Total LBAs Read" },
    { 0xAA, "Unused Reserved Block Count (Chip)" },
    { 0xAB, "Program Fail Count (Chip)" },
    { 0xAC, "Erase Fail Count (Chip)" },
    { 0xAD, "Wear Leveling Count" },
    { 0xAE, "Unexpected Power Loss Count" },
    { 0xB8, "Error Detection" },
    { 0xE9, "Normalized Media Wear-out" },
};

static const CdiAttrName kSmartSandForce[] = {
    { 0x01, "Raw Read Error Rate" },
    { 0x05, "Retired Block Count" },
    { 0x09, "Power-On Hours" },
    { 0x0C, "Power Cycle Count" },
    { 0x0D, "Soft Read Error Rate" },
    { 0x64, "Gigabytes Erased" },
    { 0xAA, "Reserve Block Count" },
    { 0xAB, "Program Fail Count" },
    { 0xAC, "Erase Fail Count" },
    { 0xAE, "Unexpected Power Loss Count" },
    { 0xB1, "Wear Range Delta" },
    { 0xB5, "Program Fail Count" },
    { 0xB6, "Erase Fail Count" },
    { 0xB8, "Reported I/O Error Detection Code Errors" },
    { 0xBB, "Reported Uncorrectable Errors" },
    { 0xC2, "Temperature" },
    { 0xC3, "On-the-Fly ECC Uncorrectable Error Count" },
    { 0xC4, "Reallocation Event Count" },
    { 0xC6, "Uncorrectable Sector Count" },
    { 0xC7, "SATA R-Errors Error Count" },
    { 0xC9, "Uncorrectable Soft Read Error Rate" },
    { 0xCC, "Soft ECC Correction Rate" },
    { 0xE6, "Drive Life Protection Status" },
    { 0xE7, "SSD Life Left" },
    { 0xE8, "Available Reserved Space" },
    { 0xEB, "Power Fail Backup Health" },
    { 0xF1, "Lifetime Writes from Host" },
    { 0xF2, "Lifetime Reads from Host" },
};

static const CdiAttrName kSmartJMicron61x[] = {
    { 0x01, "Read Error Rate" },
    { 0x02, "Throughput Performance" },
    { 0x03, "Spin-Up Time" },
    { 0x05, "Reallocated Sectors Count" },
    { 0x07, "Seek Error Rate" },
    { 0x08, "Seek Time Performance" },
    { 0x09, "Power-On Hours" },
    { 0x0A, "Spin Retry Count" },
    { 0x0C, "Power Cycle Count" },
    { 0xA8, "SATA PHY Error Count" },
    { 0xAF, "Bad Cluster Table Count (ECC Fail Count)" },
    { 0xC0, "Unexpected Power Loss Count" },
    { 0xC2, "Temperature" },
    { 0xC5, "Current Pending Sector Count" },
    { 0xAA, "Bad Block Count" },
    { 0xAD, "Erase Count" },
};

static const CdiAttrName kSmartMicron[] = {
    { 0x01, "Raw Read Error Rate" },
    { 0x05, "Reallocated NAND Blocks" },
    { 0x09, "Power On Hours" },
    { 0x0C, "Power Cycle Count" },
    { 0x0D, "Soft Error Rate" },
    { 0x0E, "Device Capacity (NAND)" },
    { 0x0F, "User Capacity" },
    { 0x10, "Spare Blocks Available" },
    { 0x11, "Remaining Spare Blocks" },
    { 0x64, "Total Erase Count" },
    { 0xAA, "Reserved Block Count" },
    { 0xAB, "Program Fail Count" },
    { 0xAC, "Erase Fail Count" },
    { 0xAD, "Average Block-Erase Count" },
    { 0xAE, "Unexpected Power Loss Count" },
    { 0xB4, "Unused Reserve NAND Blocks" },
    { 0xB5, "Unaligned Access Count" },
    { 0xB7, "SATA Interface Downshift" },
    { 0xB8, "Error Correction Count" },
    { 0xBB, "Reported Uncorrectable Errors" },
    { 0xBC, "Command Timeout Count" },
    { 0xBD, "Factory Bad Block Count" },
    { 0xC2, "Temperature" },
    { 0xC3, "Cumulative ECC Bit Correction Count" },
    { 0xC4, "Reallocation Event Count" },
    { 0xC5, "Current Pending Sector Count" },
    { 0xC6, "Smart Off-line Scan Uncorrectable Error Count" },
    { 0xC7, "Ultra DMA CRC Error Rate" },
    { 0xCA, "Percent Lifetime Used" },
    { 0xCE, "Write Error Rate" },
    { 0xD2, "Successful RAIN Recovery Count" },
    { 0xEA, "Total Bytes Read" },
    { 0xF2, "Write Protect Progress" },
    { 0xF3, "ECC Bits Corrected" },
    { 0xF4, "ECC Cumulative Threshold Events" },
    { 0xF5, "Cumulative Program NAND Pages" },
    { 0xF6, "Total Host Sector Writes" },
    { 0xF7, "Host Program Page Count" },
    { 0xF8, "Background Program Page Count" },
    { 0xF9, "Total Refresh ISP Count" },
    { 0xFA, "Total Do RefCal Count" },
    { 0xFB, "Total NAND Read Plane Count (Low 4Bytes)" },
    { 0xFC, "Total NAND Read Plane Count (High 4Bytes)" },
    { 0xFD, "Total Block ReMap Pass Count" },
    { 0xFE, "Total Background Scan Over Limit Count" },
    { 0xDF, "Total Background Scan" },
};

static const CdiAttrName kSmartMicronMU02[] = {
    { 0x01, "Raw Read Error Rate" },
    { 0x05, "Reallocated Sectors Count" },
    { 0x09, "Power-On Hours" },
    { 0x0C, "Power Cycle Count" },
    { 0x0D, "Soft Error Rate" },
    { 0x0E, "Device Capacity (NAND)" },
    { 0x0F, "User Capacity" },
    { 0x10, "Spare Blocks Available" },
    { 0x11, "Remaining Spare Blocks" },
    { 0x64, "Total Erase Count" },
    { 0xAA, "Reserved Block Count" },
    { 0xAB, "Program Fail Count" },
    { 0xAC, "Erase Fail Count" },
    { 0xAD, "Average Block-Erase Count" },
    { 0xAE, "Unexpected Power Loss Count" },
    { 0xB4, "Unused Reserve NAND Blocks" },
    { 0xB7, "SATA Interface Downshift" },
    { 0xB8, "Error Correction Count" },
    { 0xBB, "Reported Uncorrectable Errors" },
    { 0xBC, "Command Timeout Count" },
    { 0xBD, "Factory Bad Block Count" },
    { 0xC2, "Temperature" },
    { 0xC3, "Cumulative ECC Bit Correction Count" },
    { 0xC4, "Reallocation Event Count" },
    { 0xC5, "Current Pending Sector Count" },
    { 0xC6, "Smart Off-line Scan Uncorrectable Error Count" },
    { 0xC7, "Ultra DMA CRC Error Rate" },
    { 0xCA, "Percent Lifetime Used" },
    { 0xCE, "Write Error Rate" },
    { 0xD2, "Successful RAIN Recovery Count" },
    { 0xEA, "Total Bytes Read" },
    { 0xF3, "ECC Bits Corrected" },
    { 0xF4, "ECC Cumulative Threshold Events" },
    { 0xF5, "Cumulative Program NAND Pages" },
    { 0xF6, "Total Host Sector Writes" },
    { 0xF7, "Host Program Page Count" },
    { 0xF8, "Background Program Page Count" },
    { 0xA0, "Uncorrectable Sector Count" },
    { 0xA1, "Valid Spare Blocks" },
    { 0xA3, "Initial Invalid Blocks" },
    { 0x94, "Total SLC Erase Count" },
    { 0x95, "Maximum SLC Erase Count" },
    { 0x96, "Minimum SLC Erase Count" },
    { 0x97, "Average SLC Erase Count" },
    { 0xA4, "Total NAND Erase Count" },
    { 0xA5, "Maximum NAND Erase Count" },
    { 0xA6, "Minimum NAND Erase Count" },
    { 0xA7, "Average NAND Erase Count" },
    { 0xA9, "Percentage Lifetime Remaining" },
    { 0xB5, "Program Fail Count" },
    { 0xB6, "Erase Fail Count" },
    { 0xC0, "Power-off Retract Count" },
    { 0xE8, "Available Reserved Space" },
    { 0xF1, "Total LBA Write" },
    { 0xF2, "Total LBA Read" },
    { 0xF5, "Total NAND Write Count" },
    { 0xF6, "Total SLC Write Count" },
    { 0xF7, "RAID Recovery Count" },
    { 0xF9, "Total Refresh ISP Count" },
    { 0xFA, "Total Do RefCal Count" },
    { 0xFB, "Total NAND Read Plane Count (Low 4Bytes)" },
    { 0xFC, "Total NAND Read Plane Count (High 4Bytes)" },
    { 0xFD, "Total Block ReMap Pass Count" },
    { 0xFE, "Total Background Scan Over Limit Count" },
    { 0xDF, "Total Background Scan" },
};

static const CdiAttrName kSmartOcz[] = {
    { 0x01, "Raw Read Error Rate" },
    { 0x03, "Spin Up Time" },
    { 0x04, "Start Stop Count" },
    { 0x05, "Reallocated Sectors Count" },
    { 0x09, "Power-On Hours" },
    { 0x0C, "Power Cycle Count" },
    { 0xC2, "Temperature" },
    { 0xE8, "Total Count of Write Sectors" },
    { 0xE9, "Remaining Life" },
    { 0x64, "Total Blocks Erased" },
    { 0xA7, "SSD Protect Mode" },
    { 0xA8, "SATA PHY Error Count" },
    { 0xA9, "Bad Block Count" },
    { 0xAD, "Erase Count" },
    { 0xB8, "Factory Bad Block Count" },
    { 0xC0, "Unexpected Power Loss Count" },
    { 0xCA, "Total Number of Corrected Bits" },
    { 0xCD, "Max Rated PE Counts" },
    { 0xCE, "Minimum Erase Counts" },
    { 0xCF, "Maximum Erase Counts" },
    { 0xD3, "SATA Uncorrectable Error Count" },
    { 0xD4, "NAND Page Reads During Retry" },
    { 0xD5, "Simple Read Retry Attempts" },
    { 0xD6, "Adaptive Read Retry Attempts" },
    { 0xDD, "Internal Data Path Uncorrectable Errors" },
    { 0xDE, "RAID Recovery Count" },
    { 0xE6, "Power Loss Protection" },
    { 0xFB, "NAND Read Count" },
    { 0xF1, "Total Host Writes" },
    { 0xF2, "Total Host Reads" },
    { 0xF9, "Total NAND Writes" },
};

static const CdiAttrName kSmartPlextor[] = {
    { 0x01, "Read Error Rate" },
    { 0x05, "Reallocated Sectors Count" },
    { 0x09, "Power-On Hours" },
    { 0x0C, "Power Cycle Count" },
    { 0xAA, "Grown Bad Blocks" },
    { 0xAB, "Program Fail Count" },
    { 0xAC, "Erase Fail Count" },
    { 0xAD, "Average Program/Erase Count" },
    { 0xAE, "Unexpected Power Loss Count" },
    { 0xAF, "Program Fail Count (Worst Case)" },
    { 0xB0, "Erase Fail Count (Worst Case)" },
    { 0xB1, "Wear Leveling Count" },
    { 0xB2, "Used Reserved Block Count (Worst Case)" },
    { 0xB3, "Used Reserved Block Count" },
    { 0xB4, "UnUsed Reserved Block Count (Total)" },
    { 0xB5, "Program Fail Count" },
    { 0xB6, "Erase Fail Count" },
    { 0xB7, "SATA Interface Down Shift" },
    { 0xB8, "End-to-End Data Errors Corrected" },
    { 0xBB, "Uncorrectable Error Count" },
    { 0xBC, "Command Time out" },
    { 0xC0, "Unsafe Shutdown Count" },
    { 0xC3, "ECC rate" },
    { 0xC4, "Reallocation Event Count" },
    { 0xC6, "Uncorrectable Sector Count" },
    { 0xC7, "Ultra CRC Error Count" },
    { 0xE8, "Available Reserved Space" },
    { 0xE9, "NAND GB written" },
    { 0xF1, "Total Host Writes" },
    { 0xF2, "Total Host Reads" },
};

static const CdiAttrName kSmartSanDisk[] = {
    { 0x05, "Reassigned Block Count" },
    { 0x09, "Power On Hours" },
    { 0x0C, "Power Cycle Count" },
    { 0xAA, "Reserve Block Count" },
    { 0xAB, "Program Fail Count" },
    { 0xAC, "Erase Fail Count" },
    { 0xAD, "Average Write/Erase Count" },
    { 0xAE, "Unexpected Power Loss Count" },
    { 0xBB, "Reported Uncorrectable Errors" },
    { 0xC2, "Temperature" },
    { 0xE6, "Percent of Total Write/Erase Count" },
    { 0xE8, "Spare Blocks Remaining" },
    { 0xEA, "Percent of Total Write/Erase Count (BC blocks)" },
    { 0xF1, "Total Host Writes" },
    { 0xF2, "Total Host Reads" },
};

static const CdiAttrName kSmartOczVector[] = {
    { 0x05, "Accumulated Runtime Bad Blocks" },
    { 0x09, "Power-On Hours Count" },
    { 0x0C, "Power Cycle Count" },
    { 0xAB, "Available Over-Provisioned Block Count" },
    { 0xAE, "Power Cycle Count (Unplanned)" },
    { 0xBB, "Total Uncorrectable NAND Reads" },
    { 0xC2, "Temperature" },
    { 0xC3, "Total Programming Failures" },
    { 0xC4, "Total Erase Failures" },
    { 0xC5, "Total Read Failures (Uncorrectable)" },
    { 0xC6, "Host Reads" },
    { 0xC7, "Host Writes" },
    { 0xD0, "Average Erase Count" },
    { 0xD2, "SATA CRC Error Count" },
    { 0xE9, "Remaining Life" },
    { 0xF9, "Total NAND Programming Count" },
    { 0xF1, "Total Host Writes" },
    { 0xF2, "Total Host Reads" },
    { 0x64, "Total Blocks Erased" },
    { 0xB8, "Factory Bad Block Count Total" },
    { 0xCA, "Total Number Of Read Bits Corrected" },
    { 0xCD, "Max Rated PE Count" },
    { 0xCE, "Min Erase Count" },
    { 0xCF, "Max Erase Count" },
    { 0xD4, "Total Count NAND Pages Reads Requiring Read Retry" },
    { 0xD5, "Total Count of Simple Read Retry Attempts" },
    { 0xD6, "Total Count of Adaptive Read Retry Attempts" },
    { 0xDD, "Internal Data Path Protection Uncorrectable Errors" },
    { 0xDE, "RAID Recovery Count" },
    { 0xE0, "In Warranty" },
    { 0xE1, "DAS Polarity" },
    { 0xE2, "Partial Pfail" },
    { 0xE6, "Write Throttling Activation Flag" },
    { 0xF9, "Total NAND Programming Count (pages)" },
    { 0xFB, "Total NAND Read Count" },
};

static const CdiAttrName kSmartCorsair[] = {
    { 0x01, "Raw Read Error Rate" },
    { 0x05, "Retired Block Count" },
    { 0x09, "Power On Hours" },
    { 0x0C, "Power Cycle Count" },
    { 0xAA, "Reserve Block Count" },
    { 0xAC, "Erase Fail Count" },
    { 0xAE, "Unexpected Power Loss Count" },
    { 0xB5, "Program Fail Count" },
    { 0xBB, "Reported Uncorrectable Errors" },
    { 0xC2, "Temperature" },
    { 0xC4, "Reallocation Event Count" },
    { 0xE7, "SSD Life Left" },
    { 0xF1, "Lifetime Written" },
    { 0xF2, "Lifetime Read" },
};

static const CdiAttrName kSmartToshiba[] = {
    { 0x01, "Read Error Rate" },
    { 0x02, "Throughput Performance" },
    { 0x03, "Spin-Up Time" },
    { 0x04, "Start/Stop Count" },
    { 0x05, "Reallocated Sectors Count" },
    { 0x07, "Seek Error Rate" },
    { 0x08, "Seek Time Performance" },
    { 0x09, "Power-On Hours" },
    { 0x0A, "Spin Retry Count" },
    { 0x0B, "Recalibration Retries" },
    { 0x0C, "Power Cycle Count" },
    { 0xA7, "SSD Protect Mode" },
    { 0xA8, "SATA PHY Error Count" },
    { 0xA9, "Total Bad Block Count" },
    { 0xAD, "Erase Count" },
    { 0xC0, "Unexpected Power Loss Count" },
    { 0xC2, "Temperature" },
    { 0xC4, "Reallocation Event Count" },
    { 0xC5, "Current Pending Sector Count" },
    { 0xC6, "Uncorrectable Sector Count" },
    { 0xF1, "Total Host Writes" },
    { 0xF2, "Total Host Reads" },
};

static const CdiAttrName kSmartSanDiskGb[] = {
    { 0x01, "Read Error Rate" },
    { 0x05, "Reassigned Block Count" },
    { 0x09, "Power On Hours" },
    { 0x0C, "Power Cycle Count" },
    { 0xA5, "Block Erase Count (SLC)" },
    { 0xA6, "Minimum P/E Cycles" },
    { 0xA7, "Maximum Bad Blocks per die" },
    { 0xA8, "Maximum P/E Cycles" },
    { 0xA9, "Total Bad Block" },
    { 0xAA, "Grown Bad Blocks" },
    { 0xAB, "Program Fail Count" },
    { 0xAC, "Erase Fail Count" },
    { 0xAD, "Average P/E Cycles" },
    { 0xAE, "Unexpected Power Loss Count" },
    { 0xB8, "End-to-End Error Detection/Correction Count" },
    { 0xBB, "Reported Uncorrectable Errors" },
    { 0xBC, "Command Timeout Count" },
    { 0xC2, "Temperature" },
    { 0xC7, "CRC Error Count" },
    { 0xD4, "SATA PHY Error" },
    { 0xE6, "Media Wearout Indicator" },
    { 0xE7, "SSD Life Left" },
    { 0xE8, "Available Reserve Space" },
    { 0xE9, "NAND GB Written" },
    { 0xEA, "NAND GB Written (SLC)" },
    { 0xEE, "Media Wearout Indicator (Cycles Remaining)" },
    { 0xF1, "Total GB Written" },
    { 0xF2, "Total GB Read" },
    { 0xF4, "Temperature Throttle Status" },
    { 0xF9, "NAND GB Written" },
};

static const CdiAttrName kSmartKingston[] = {
    { 0x01, "Read Error Rate" },
    { 0x02, "Throughput Performance" },
    { 0x03, "Spin Up Time" },
    { 0x05, "Reallocated Sectors Count" },
    { 0x07, "Seek Error Rate" },
    { 0x08, "Seek Time Performance" },
    { 0x09, "Power-On Hours" },
    { 0x0A, "Spin Retry Count" },
    { 0x0C, "Power Cycle Count" },
    { 0xA8, "SATA PHY Error Count" },
    { 0xAA, "Bad Block Count" },
    { 0xAD, "Erase count" },
    { 0xAF, "Bad Cluster Table Count" },
    { 0xBB, "Uncorrectable Errors" },
    { 0xC0, "Unsafe Shutdown Count" },
    { 0xC2, "Temperature" },
    { 0xC4, "Later Bad Block Count" },
    { 0xC5, "Current Pending Sector Count" },
    { 0xC7, "CRC Error Count" },
    { 0xDA, "CRC Error Count" },
    { 0xE7, "SSD Life Left" },
    { 0xE9, "Lifetime Writes to Flash" },
    { 0xF0, "Write Head" },
    { 0xF1, "Host Writes" },
    { 0xF2, "Host Reads" },
    { 0xF4, "Average Erase Count" },
    { 0xF5, "Max Erase Count" },
    { 0xF6, "Total Erase Count" },
};

static const CdiAttrName kSmartNVMe[] = {
    { 0x01, "Critical Warning" },
    { 0x02, "Composite Temperature" },
    { 0x03, "Available Spare" },
    { 0x04, "Available Spare Threshold" },
    { 0x05, "Percentage Used" },
    { 0x06, "Data Units Read" },
    { 0x07, "Data Units Written" },
    { 0x08, "Host Read Commands" },
    { 0x09, "Host Write Commands" },
    { 0x0A, "Controller Busy Time" },
    { 0x0B, "Power Cycles" },
    { 0x0C, "Power On Hours" },
    { 0x0D, "Unsafe Shutdowns" },
    { 0x0E, "Media and Data Integrity Errors" },
    { 0x0F, "Number of Error Information Log Entries" },
    { 0x10, "Warning Composite Temperature Time" },
    { 0x11, "Critical Composite Temperature Time" },
    { 0x12, "Temperature Sensor 1" },
    { 0x13, "Temperature Sensor 2" },
    { 0x14, "Temperature Sensor 3" },
    { 0x15, "Temperature Sensor 4" },
    { 0x16, "Temperature Sensor 5" },
    { 0x17, "Temperature Sensor 6" },
    { 0x18, "Temperature Sensor 7" },
    { 0x19, "Temperature Sensor 8" },
    { 0x1A, "Thermal Management Temperature 1 Transition Count" },
    { 0x1B, "Thermal Management Temperature 2 Transition Count" },
    { 0x1C, "Total Time For Thermal Management Temperature 1" },
    { 0x1D, "Total Time For Thermal Management Temperature 2" },
};

static const CdiAttrName kSmartRealtek[] = {
    { 0x01, "Raw data error rate" },
    { 0x05, "Reallocated sector count" },
    { 0x09, "Power on hour count" },
    { 0x0C, "Power cycle count" },
    { 0xA1, "GDN" },
    { 0xA2, "Total erase count" },
    { 0xA3, "Max PE cycle" },
    { 0xA4, "Average erase count" },
    { 0xA5, "Initial bad block count" },
    { 0xA6, "Total bad block count" },
    { 0xA7, "SSD protect mode" },
    { 0xA8, "SATA Phy error count" },
    { 0xA9, "Health" },
    { 0xAB, "Program fail count" },
    { 0xAC, "Erase fail count" },
    { 0xAE, "Unexpected power loss count" },
    { 0xAF, "ECC fail count" },
    { 0xB5, "Unaligned access count" },
    { 0xBB, "Reported uncorrectable error" },
    { 0xC2, "Enclosure temperature" },
    { 0xC3, "Cumulative corrected ecc" },
    { 0xC4, "Reallocation event count" },
    { 0xC7, "Ultra DMA CRC error count" },
    { 0xCE, "Min. erase count" },
    { 0xCF, "Max erase count" },
    { 0xE7, "Lifetime left" },
    { 0xE8, "Available reserved space" },
    { 0xF1, "Write life time" },
    { 0xF2, "Read life time" },
    { 0xF9, "Total GB written to NAND" },
    { 0xFA, "Total GB written to NAND (SLC)" },
};

static const CdiAttrName kSmartSKhynix[] = {
    { 0x01, "Read Error Rate" },
    { 0x05, "Re-Assigned Sector Count" },
    { 0x09, "Power-On Hours" },
    { 0x0C, "Power Cycle Count" },
    { 0x64, "Total Erase Count" },
    { 0xA8, "Min. Erase Count" },
    { 0xA9, "Max. Erase Count" },
    { 0xAA, "Reserve Block Count" },
    { 0xAB, "Program Fail Count" },
    { 0xAC, "Erase Fail Count" },
    { 0xAE, "Unexpected Power Loss Count" },
    { 0xAF, "Program Fail Count(Worst Case)" },
    { 0xB0, "Erase Fail Count(Worst Case)" },
    { 0xB1, "Wear Leveling Count" },
    { 0xB2, "Used Reseved Block Count(Worst Case)" },
    { 0xB3, "Used Reseved Block Count(SSD Total)" },
    { 0xB4, "UnUsed Reseved Block Count(SSD Total)" },
    { 0xB5, "Program Fail Count(SSD Total)" },
    { 0xB6, "Erase Fail Count(SSD Total)" },
    { 0xB7, "SATA Downshift Count" },
    { 0xB8, "End-to-End Error Detection Count" },
    { 0xBB, "Uncorrectable Error Count" },
    { 0xBC, "Command Timeout Count" },
    { 0xBF, "Op Shock Event Count" },
    { 0xC2, "Temperature" },
    { 0xC3, "ECC Rate" },
    { 0xC4, "Reallocation Event Count" },
    { 0xC6, "Uncorrectable Sector Count" },
    { 0xC7, "CRC Error Count" },
    { 0xC9, "Uncorrectable Soft Read Error Rate" },
    { 0xCC, "Soft ECC Correction Rate" },
    { 0xD4, "Phy Error Count" },
    { 0xE7, "SSD Life Left" },
    { 0xE9, "SSD Life Left" },
    { 0xEA, "NAND Written" },
    { 0xF1, "Total LBA Written" },
    { 0xF2, "Total LBA Read" },
    { 0xFA, "Total Number of NAND Read Retries" },
};

static const CdiAttrName kSmartKioxia[] = {
    { 0x09, "Power-On Hours Count" },
    { 0x0C, "Power Cycle Count" },
    { 0xA7, "SSD Protect Mode" },
    { 0xA8, "SATA PHY Error Count" },
    { 0xA9, "Bad Block Count" },
    { 0xAD, "Erase Count (User Data)" },
    { 0xC0, "Unexpected Power Loss Count" },
    { 0xC2, "Temperature" },
    { 0xF1, "Host Writes" },
};

static const CdiAttrName kSmartWdc[] = {
    { 0x01, "Read Error Rate" },
    { 0x05, "Reassigned Block Count" },
    { 0x09, "Power On Hours" },
    { 0x0C, "Power Cycle Count" },
    { 0xA5, "Block Erase Count (SLC)" },
    { 0xA6, "Minimum P/E Cycles" },
    { 0xA7, "Maximum Bad Blocks per die" },
    { 0xA8, "Maximum P/E Cycles" },
    { 0xA9, "Total Bad Block" },
    { 0xAA, "Grown Bad Blocks" },
    { 0xAB, "Program Fail Count" },
    { 0xAC, "Erase Fail Count" },
    { 0xAD, "Average P/E Cycles" },
    { 0xAE, "Unexpected Power Loss Count" },
    { 0xB8, "End-to-End Error Detection/Correction Count" },
    { 0xBB, "Reported Uncorrectable Errors" },
    { 0xBC, "Command Timeout Count" },
    { 0xC2, "Temperature" },
    { 0xC7, "CRC Error Count" },
    { 0xD4, "SATA PHY Error" },
    { 0xE6, "Media Wearout Indicator" },
    { 0xE8, "Available Reserve Space" },
    { 0xE9, "NAND GB Written" },
    { 0xEA, "NAND GB Written (SLC)" },
    { 0xEE, "Media Wearout Indicator (Cycles Remaining)" },
    { 0xF1, "Total GB Written" },
    { 0xF2, "Total GB Read" },
    { 0xF3, "Total NAND Writes" },
    { 0xF4, "Temperature Throttle Status" },
    { 0xF9, "NAND GB Written" },
};

static const CdiAttrName kSmartKingstonSuv[] = {
    { 0x01, "Read Error Rate" },
    { 0x05, "Reallocated Sector Count" },
    { 0x09, "Power On Hours" },
    { 0x0C, "Power Cycle Count" },
    { 0xAA, "Used Reserved Block Count" },
    { 0xAB, "Program Fail Count" },
    { 0xAC, "Erase Fail Count" },
    { 0xAE, "Unexpected Power Off Count" },
    { 0xAF, "Program Fail Count Worst Die" },
    { 0xB0, "Erase Fail Count Worst Die" },
    { 0xB1, "Wear Leveling Count" },
    { 0xB2, "Used Reserved Block Count worst Die" },
    { 0xB4, "Unused Reserved Block Count (SSD Total)" },
    { 0xBB, "Reported Uncorrectable Errors" },
    { 0xC2, "Temperature" },
    { 0xC3, "On-the-Fly ECC Error Count" },
    { 0xC4, "Reallocation Event Count" },
    { 0xC5, "Pending Sector Count" },
    { 0xC7, "UDMA CRC Error Count" },
    { 0xC9, "Uncorrectable Read Error Rate" },
    { 0xCC, "Soft ECC Correction Rate" },
    { 0xE7, "SSD Life Left" },
    { 0xEA, "Lifetime Nand Writes" },
    { 0xF1, "Lifetime Host Writes" },
    { 0xF2, "Lifetime Host Reads" },
    { 0xFA, "Total Number of NAND Read Retries" },
};

static const CdiAttrName kSmartKingstonKC600[] = {
    { 0x01, "Read Error Rate" },
    { 0x05, "Re-Allocated NAND Block Count" },
    { 0x09, "Power-On Hours" },
    { 0x0C, "Power Cycle Count" },
    { 0x94, "Reserved" },
    { 0x95, "Reserved" },
    { 0x96, "Reserved" },
    { 0x97, "SLC Average Erase Count" },
    { 0x9F, "DRAM 1 bit Error Count" },
    { 0xA0, "Reported UECC (UnCorrectable) Errors" },
    { 0xA1, "Available Reserved Space" },
    { 0xA4, "Reserved" },
    { 0xA5, "Reserved" },
    { 0xA6, "Reserved" },
    { 0xA7, "Average Erase Count" },
    { 0xA8, "Reserved" },
    { 0xA9, "Percentage Of Rated Lifetime Remaining" },
    { 0xB1, "Reserved" },
    { 0xB5, "Program Fail Count" },
    { 0xB6, "Erase Fail Count" },
    { 0xC0, "Unexpected Power Loss Count" },
    { 0xC2, "Device Temperature" },
    { 0xC3, "Hardware ECC Recovered" },
    { 0xC4, "Reallocation Event Count" },
    { 0xC7, "UDMA CRC Error Count" },
    { 0xE7, "Percentage of Rated Lifetime Remaining" },
    { 0xE8, "Unused Reserved Block Count" },
    { 0xF1, "Total LBAs Written" },
    { 0xF2, "Total LBAs Read" },
    { 0xF5, "Total Media Writes" },
};

static const CdiAttrName kSmartKingstonDC500[] = {
    { 0x01, "Host UNC Error Count" },
    { 0x09, "Power on Hours" },
    { 0x0C, "Power On / Off Cycle" },
    { 0xA7, "Protect mode" },
    { 0xA8, "SATA PHY Error Count" },
    { 0xA9, "Bad Block Rate" },
    { 0xAA, "Bad Block Information" },
    { 0xAC, "Erase Failure Count" },
    { 0xAD, "Erase Count" },
    { 0xB5, "Program Fail Count" },
    { 0xB6, "Erase Failure Count" },
    { 0xBB, "Host UNC Error Count" },
    { 0xC0, "Unexpected Power Loss Count" },
    { 0xC2, "Temperature" },
    { 0xC4, "Total Later Bad Block Count" },
    { 0xC7, "CRC Error Count" },
    { 0xCF, "Thermal Throttling Count" },
    { 0xDA, "CRC Error Count" },
    { 0xE7, "SSD Life Remaining" },
    { 0xE8, "Read Fail Count" },
    { 0xE9, "NAND Write" },
    { 0xF1, "Host Write" },
    { 0xF2, "Host Read" },
    { 0xF4, "Avg Erase Count" },
    { 0xF5, "Max Erase Count" },
    { 0xF6, "Total Erase Count" },
};

static const CdiAttrName kSmartKingstonSA400[] = {
    { 0x01, "Uncorrectable Errors" },
    { 0x09, "Power On Hours" },
    { 0x0C, "Power Cycles" },
    { 0x94, "Vendor Unique" },
    { 0x95, "Vendor Unique" },
    { 0xA7, "Vendor Unique" },
    { 0xA8, "SATA PHY Error Count" },
    { 0xA9, "Vendor Unique" },
    { 0xAA, "Bad Block Count" },
    { 0xAC, "Vendor Unique" },
    { 0xAD, "Erase Count" },
    { 0xB5, "Vendor Unique" },
    { 0xB6, "Vendor Unique" },
    { 0xBB, "Uncorrectable ECC Errors" },
    { 0xC2, "Temperature" },
    { 0xC4, "Reallocation Events" },
    { 0xC7, "SATA CRC Error" },
    { 0xDA, "CRC Error Count" },
    { 0xE7, "SSD Wear Indicator" },
    { 0xE9, "Lifetime Nand Writes" },
    { 0xF1, "Lifetime Writes from Host" },
    { 0xF2, "Lifetime Read from Host" },
    { 0xF4, "Average Erase Count" },
    { 0xF5, "Max Erase Count" },
    { 0xF6, "Total Erase Count" },
};

static const CdiAttrName kSmartSsstc[] = {
    { 0x01, "Raw Read Error Rate" },
    { 0x05, "Reallocated Block Count" },
    { 0x09, "Power On Hours" },
    { 0x0C, "Power Cycle Count" },
    { 0xAA, "Available Reserved Space" },
    { 0xAB, "Program Fail Count (Total)" },
    { 0xAC, "Erase Fail Count (Total)" },
    { 0xAD, "Average Program/Erase Count" },
    { 0xAE, "Unexpected Power Loss Count" },
    { 0xAF, "Program Fail count (Worst case)" },
    { 0xB0, "Erase Fail Count (Worst case)" },
    { 0xB1, "Wear Leveling Count" },
    { 0xB2, "Used Reserved Block Count (Worst case)" },
    { 0xB3, "Used Reserved Block Count (Total)" },
    { 0xB4, "Unused Reserved Block Count (Total)" },
    { 0xB7, "SATA Interface Down shift" },
    { 0xB8, "End-to-End Data Errors Count" },
    { 0xBB, "Uncorrectable Error Count" },
    { 0xBC, "Command Time out" },
    { 0xC2, "Drive Temperature" },
    { 0xC3, "ECC rate" },
    { 0xC6, "OffLine Uncorrectable Error Count" },
    { 0xC7, "SATA CRC Error Count" },
    { 0xE5, "Power Loss Protection Failure" },
    { 0xE7, "Percentage Lifetime Remaining" },
    { 0xE8, "Available Reserved Space" },
    { 0xE9, "NAND GB Written" },
    { 0xF1, "Total Host Write" },
    { 0xF2, "Total Host Read" },
    { 0xF3, "NAND GB Written" },
};

static const CdiAttrName kSmartIntelDc[] = {
    { 0x01, "Raw Read Error Count" },
    { 0x05, "Reallocated Flash Block Count" },
    { 0x09, "Power-On Hours Count" },
    { 0x0C, "Power Cycle Count" },
    { 0x0E, "Device Capacity" },
    { 0x0F, "User Capacity" },
    { 0x10, "Spare Blocks Available" },
    { 0x11, "Remaining Spare Available" },
    { 0xAC, "Total Block Erase Failure" },
    { 0xAD, "Per Block Max Erase Count" },
    { 0xAE, "Unexpected Power Loss Count" },
    { 0xAF, "Average Erase Count" },
    { 0xB0, "Power Loss Protection Error" },
    { 0xB5, "Total Block Program Failure" },
    { 0xB8, "End-to-End Error Detection Count" },
    { 0xBB, "Uncorrectable Error Count" },
    { 0xC2, "Temperature" },
    { 0xC5, "Pending Sector Count" },
    { 0xC6, "Offline Uncorrectable Error Count" },
    { 0xC7, "CRC Error Count" },
    { 0xCA, "Percentage of Drive Life Used" },
    { 0xE2, "Timed Workload - Media Wear" },
    { 0xE3, "Timed Workload - Host Read/Write Ratio" },
    { 0xE4, "Timed Workload Timer" },
    { 0xEA, "Thermal Throttle Status" },
    { 0xEB, "Total Host Bytes/Sectors Written" },
    { 0xF1, "Total Nand Bytes/Sectors Written" },
};

static const CdiAttrName kSmartApacer[] = {
    { 0x09, "Power on Hours" },
    { 0x0C, "Power Cycle Count" },
    { 0xA3, "Maximum Erase Count" },
    { 0xA4, "Average Erase Count" },
    { 0xA6, "Total Later Bad Block Count" },
    { 0xA7, "SSD Protect Mode" },
    { 0xA8, "SATA PHY Error Count" },
    { 0xAB, "Program Fail Count" },
    { 0xAC, "Erase Fail Count" },
    { 0xAF, "Bad Cluster Table Count" },
    { 0xC0, "Unexpected Power Loss Count" },
    { 0xC2, "Temperature" },
    { 0xE7, "Lifetime Left" },
    { 0xF1, "Total Sectors Write" },
};

static const CdiAttrName kSmartSiliconMotion[] = {
    { 0x01, "Read Error Rate" },
    { 0x05, "Reallocated Sectors Count" },
    { 0x09, "Power-On Hours" },
    { 0x0C, "Power Cycle Count" },
    { 0x94, "SLC Total Erase Count" },
    { 0x95, "SLC Maximum Erase Count" },
    { 0x96, "SLC Minimum Erase Count" },
    { 0x97, "SLC Average Erase Count" },
    { 0x9F, "DRAM 1 bit Error Count" },
    { 0xA0, "Uncorrectable sectors count when read/write" },
    { 0xA1, "Number of Valid Spare Blocks" },
    { 0xA2, "Number of Cache Data Block" },
    { 0xA3, "Number of Initial Invalid Blocks" },
    { 0xA4, "Total Erase Count" },
    { 0xA5, "Maximum Erase Count" },
    { 0xA6, "Minimum Erase Count" },
    { 0xA7, "Average Erase Count" },
    { 0xA8, "Max Erase Count of Spec" },
    { 0xA9, "Remain Life" },
    { 0xAF, "Program fail count in worst die" },
    { 0xB0, "Erase fail count in worst die" },
    { 0xB1, "Total Wear Level Count" },
    { 0xB2, "Runtime Invalid Block Count" },
    { 0xB5, "Total Program Fail Count" },
    { 0xB6, "Total Erase Fail Count" },
    { 0xBB, "Uncorrectable Error Count" },
    { 0xC0, "Power-Off Retract Count" },
    { 0xC2, "Temperature" },
    { 0xC3, "Hardware ECC Recovered" },
    { 0xC4, "Reallocation Event Count" },
    { 0xC5, "Current Pending Sector Count" },
    { 0xC6, "Uncorrectable Error Count Off-line" },
    { 0xC7, "Ultra DMA CRC Error Count" },
    { 0xE8, "Available Reserved Space" },
    { 0xF1, "Total LBA Written" },
    { 0xF2, "Total LBA Read" },
    { 0xF5, "Flash Write Sector Count" },
};

static const CdiAttrName kSmartJMicron66x[] = {
    { 0x01, "Read Error Rate" },
    { 0x02, "Throughput Performance" },
    { 0x03, "Spin-Up Time" },
    { 0x05, "Reallocated Sectors Count" },
    { 0x07, "Seek Error Rate" },
    { 0x08, "Seek Time Performance" },
    { 0x09, "Power-On Hours" },
    { 0x0A, "Spin Retry Count" },
    { 0x0C, "Power Cycle Count" },
    { 0xA7, "SSD Protect Mode" },
    { 0xA8, "SATA PHY Error Count" },
    { 0xAA, "Bad Block Count" },
    { 0xAD, "Erase Count" },
    { 0xAF, "Bad Cluster Table Count" },
    { 0xB4, "Spare Block Count" },
    { 0xC0, "Unexpected Power Loss Count" },
    { 0xC2, "Temperature" },
    { 0xC5, "Current Pending Sector Count" },
    { 0xE7, "Drive Life" },
    { 0xE9, "Write Sector Count (NAND)" },
    { 0xF0, "Write Head" },
    { 0xF1, "Total LBA Written" },
    { 0xF2, "Total LBA Read" },
};

static const CdiAttrName kSmartPhison[] = {
    { 0x01, "Read Error Rate" },
    { 0x09, "Power on Hours" },
    { 0x0C, "Power Cycle Count" },
    { 0xA8, "SATA PHY Error Count" },
    { 0xAA, "Bad Block Count" },
    { 0xAD, "Erase Count" },
    { 0xC0, "Unexpected Power Loss Count" },
    { 0xC2, "Temperature" },
    { 0xDA, "Number of CRC Error" },
    { 0xE7, "SSD Life Left" },
    { 0xF1, "Host Writes" },
};

static const CdiAttrName kSmartSeagate[] = {
    { 0x01, "Read Error Rate" },
    { 0x05, "Retired Sectors Count" },
    { 0x09, "Power On Hours" },
    { 0x0C, "Power Cycle Count" },
    { 0x10, "Spare Blocks Available" },
    { 0x11, "Remaining Spare Blocks" },
    { 0xA8, "SATA PHY Error Count" },
    { 0xAA, "Bad Block Count" },
    { 0xAB, "Program Fail Count" },
    { 0xAC, "Erase Fail Count" },
    { 0xAD, "Erase Count" },
    { 0xAE, "Unexpected Power Loss Count" },
    { 0xB1, "Wear Range Delta" },
    { 0xB5, "Program Fail Count" },
    { 0xB6, "Erase Fail Count" },
    { 0xC0, "Unexpected Power loss Count" },
    { 0xC2, "Temperature" },
    { 0xC9, "Soft Error Rate" },
    { 0xCC, "Soft ECC Correction Rate" },
    { 0xDA, "CRC Error Count" },
    { 0xE7, "SSD Life Left" },
    { 0xE8, "Read Failure Block Count" },
    { 0xE9, "NAND GiB Written" },
    { 0xEA, "Lifetime Writes To Flash" },
    { 0xEB, "NAND sectors Written" },
    { 0xF1, "Lifetime Writes From Host" },
    { 0xF2, "Lifetime Reads From Host" },
    { 0xFA, "Lifetime NAND Read Retries" },
};

static const CdiAttrName kSmartSeagateIronWolf[] = {
    { 0x01, "Raw Read Error Rate" },
    { 0x05, "Reallocated Sector Count" },
    { 0x09, "Power On Hours" },
    { 0x0C, "Power Cycle Count" },
    { 0x64, "Flash Gigabytes Erased" },
    { 0x66, "Lifetime PS4 Entry Count" },
    { 0x67, "Lifetime PS3 Entry Count" },
    { 0xAA, "Grown Bad Block Count" },
    { 0xAB, "Program Fail Count" },
    { 0xAC, "Erase Fail Count" },
    { 0xAD, "Average Program/Erase Count" },
    { 0xAE, "Unexpected Power Loss Count" },
    { 0xB1, "Wear Range Delta" },
    { 0xB7, "SATA/PCIe Interface Downshift Count" },
    { 0xBB, "Uncorrectable ECC Count" },
    { 0xC2, "Temperature" },
    { 0xC3, "RAISE ECC Correctable Count" },
    { 0xC6, "Uncorrectable Read Error Count" },
    { 0xC7, "SATA R-Error (CRC) Error Count" },
    { 0xE6, "Drive Life Protection Status" },
    { 0xE7, "SSD Life Left" },
    { 0xE8, "Available Reserved Space" },
    { 0xE9, "Lifetime Writes to Flash" },
    { 0xF1, "Lifetime Writes From Host" },
    { 0xF2, "Lifetime Reads From Host" },
    { 0xF3, "Free Space" },
};

static const CdiAttrName kSmartMarvell[] = {
    { 0x05, "Number of New Bad Block" },
    { 0x09, "Power On Hours" },
    { 0x0C, "Power Cycle Count" },
    { 0xA4, "Total Erase Count" },
    { 0xA5, "Maximum Erase Count" },
    { 0xA6, "Minimum Erase Count" },
    { 0xA7, "Average Erase Count" },
    { 0xC0, "Power off Retract Count" },
    { 0xC2, "Temperature" },
    { 0xC7, "SATA CRC Error Count" },
    { 0xF1, "Total Written" },
    { 0xF2, "Total Read" },
};

static const CdiAttrName kSmartMaxiotek[] = {
    { 0x05, "Reallocated Sector Count" },
    { 0x09, "Power-On Hours" },
    { 0x0C, "Power Cycle Count" },
    { 0xA7, "SSD Protect Mode" },
    { 0xA8, "PHY Error Count" },
    { 0xA9, "Bad Block Count" },
    { 0xAB, "Program Fail Count" },
    { 0xAC, "Erase Fail Count" },
    { 0xAD, "Erase Count" },
    { 0xAF, "Bad Cluster Table Count" },
    { 0xB1, "Read Retry Count" },
    { 0xB4, "Spare Block Count Left" },
    { 0xBB, "Reported UNC Errors" },
    { 0xC0, "Unexpected Power Loss Count" },
    { 0xC2, "Temperature" },
    { 0xC4, "Reallocated Event Count" },
    { 0xC7, "UDMA CRC Error Count" },
    { 0xCE, "Minimum Erase Count" },
    { 0xCF, "Maximum Erase Count" },
    { 0xD0, "Average Erase Count" },
    { 0xD1, "Minimum Erase Count of SLC block" },
    { 0xD2, "Maximum Erase Count of SLC block" },
    { 0xD3, "Average Erase Count of SLC block" },
    { 0xE7, "SSD Life Left" },
    { 0xE9, "Write Counts Sectors to Nand" },
    { 0xEA, "Read Counts Sectors from Nand" },
    { 0xF1, "Write Sector Count" },
    { 0xF2, "Read Sector Count" },
    { 0xF5, "Bit Error Count" },
};

static const CdiAttrName kSmartSeagateBarraCuda[] = {
    { 0x01, "UECC Error Count" },
    { 0x05, "Retired Sectors Count" },
    { 0x09, "Power On Hours" },
    { 0x0C, "Power Cycle Count" },
    { 0x10, "Spare Blocks Available" },
    { 0x11, "Remaining Spare Blocks" },
    { 0xA8, "SATA PHY Error Count" },
    { 0xAA, "Bad Block Count" },
    { 0xAB, "Program Fail Count" },
    { 0xAC, "Erase Fail Count" },
    { 0xAD, "Erase Count" },
    { 0xAE, "Unexpected Power Loss Count" },
    { 0xB1, "Wear Range Delta" },
    { 0xB5, "Program Fail Count" },
    { 0xB6, "Erase Fail Count" },
    { 0xC0, "Unexpected Power loss Count" },
    { 0xC2, "Temperature" },
    { 0xC9, "Soft Error Rate" },
    { 0xCC, "Soft ECC Correction Rate" },
    { 0xDA, "CRC Error Count" },
    { 0xE7, "SSD Life Left" },
    { 0xE8, "Read Failure Block Count" },
    { 0xE9, "NAND GiB Written" },
    { 0xEA, "Lifetime Writes To Flash" },
    { 0xEB, "NAND sectors Written" },
    { 0xF1, "Lifetime Writes From Host" },
    { 0xF2, "Lifetime Reads From Host" },
    { 0xFA, "Lifetime NAND Read Retries" },
};

static const CdiAttrName kSmartYmtc[] = {
    { 0x05, "New Bad Block Count" },
    { 0x09, "Power-On Hours Count" },
    { 0x0C, "Power Cycle Count" },
    { 0xAA, "Max Bad Block Count" },
    { 0xA8, "SATA PHY Error Count" },
    { 0xA9, "Bad Block Count" },
    { 0xAB, "Program Fail Count" },
    { 0xAC, "Erase Fail Count" },
    { 0xAD, "Erase Count" },
    { 0xAF, "Bad Cluster Count" },
    { 0xB7, "SATA Interface Downshift" },
    { 0xB8, "End to End Error Detection/Correction Count" },
    { 0xBB, "Uncorrectable Error Count" },
    { 0xBE, "Temperature" },
    { 0xC0, "Unexpected Power Loss Count" },
    { 0xC4, "Re-allocated Event Count" },
    { 0xC7, "CRC Error Count" },
    { 0xCE, "Minimum Erase Count" },
    { 0xCF, "Maximum Erase Count" },
    { 0xD0, "Average Erase Count" },
    { 0xD1, "SLC Minimum Erase Count" },
    { 0xD2, "SLC Maximum Erase Count" },
    { 0xD3, "SLC Average Erase Count" },
    { 0xE7, "SSD Life Left" },
    { 0xE9, "Write sector count to NAND" },
    { 0xEA, "Read sector count to NAND" },
    { 0xF1, "Total LBA written" },
    { 0xF2, "Total LBA Read" },
    { 0xF3, "NAND Temperature" },
    { 0xF5, "Bit Error Count" },
};

static const CdiAttrName kSmartScy[] = {
    { 0x01, "Raw Read Error Rate" },
    { 0x05, "Reallocated Sector Count" },
    { 0x07, "Seek Error Rate" },
    { 0x09, "Power-On Hours" },
    { 0x0C, "Drive Power Cycle Count" },
    { 0xA7, "Average Erase Count" },
    { 0xAB, "Program Fail Count" },
    { 0xAC, "Erase Fail Count" },
    { 0xAD, "Erase Count" },
    { 0xB1, "Read Retry Count" },
    { 0xB4, "Spare Block Count Left" },
    { 0xB7, "Runtime Bad Block" },
    { 0xBB, "Reported UNC Errors" },
    { 0xC0, "Unexpected Power Loss Count" },
    { 0xC2, "Controlled Temperature" },
    { 0xC3, "Cumulative ECC Bit Correction Count" },
    { 0xC4, "Reallocated Event Count" },
    { 0xC5, "Current Pending Sector" },
    { 0xC7, "UDMA CRC Error Count" },
    { 0xE7, "SSD Life Left" },
    { 0xF1, "Total LBAs Written" },
    { 0xF2, "Total LBAs Read" },
    { 0xF5, "Total Nand Flash Written" },
};

static const CdiAttrName kSmartRecadata[] = {
    { 0x07, "Seek Error Rate" },
    { 0x09, "Power-On Hours" },
    { 0x0C, "Drive Power Cycle Count" },
    { 0xA7, "Average erase count" },
    { 0xAB, "Program Fail Count" },
    { 0xAC, "Erase Fail Count" },
    { 0xAD, "Erase Count" },
    { 0xB1, "Read Retry Count" },
    { 0xB4, "Spare Block Count Left" },
    { 0xB7, "Runtime Bad Block" },
    { 0xBB, "Reported UNC Errors" },
    { 0xC0, "Unexpected Power Loss Count" },
    { 0xC2, "Controlled temperature" },
    { 0xC3, "Cumulative ECC Bit Correction Count" },
    { 0xC4, "Reallocated Event Count" },
    { 0xC5, "Current Pending Sector" },
    { 0xC7, "UDMA CRC Error Count" },
    { 0xE7, "SSD Life Left" },
    { 0xF1, "Total LBAs written" },
    { 0xF2, "Total LBAs read" },
    { 0xF5, "Total Nand Flash Written" },
};

static const CdiAttrName kSmartSanDiskHp[] = {
    { 0x01, "Raw Read Error Rate" },
    { 0x05, "Reassigned Block Count" },
    { 0x09, "Power On Hours" },
    { 0x0C, "Drive Power Cycle Count" },
    { 0xAA, "Reserved Block Count" },
    { 0xAB, "Program Fail Count" },
    { 0xAC, "Erase Fail Count" },
    { 0xAD, "Wear Leveling Count" },
    { 0xAE, "Unexpected Power Loss Count" },
    { 0xB0, "Unused Reserved Block Count" },
    { 0xB7, "SATA Interface Downshift Count" },
    { 0xB8, "End to End Error Detection/Correction Count" },
    { 0xBB, "Uncorrectable Error Count" },
    { 0xBC, "Command Time Out" },
    { 0xBE, "Airflow Temperature" },
    { 0xC2, "Temperature" },
    { 0xC4, "Reallocated Event Count" },
    { 0xC7, "CRC Error Count" },
    { 0xC9, "SSD Life Left" },
    { 0xE6, "Media Wearout Indicator" },
    { 0xF1, "Total LBAs Written" },
    { 0xF2, "Total LBAs Read" },
    { 0xF3, "Throttle Statistics" },
    { 0xF4, "Temperature Throttle Status" },
    { 0xF9, "TLC NAND GB Writes" },
};

static const CdiAttrName kSmartSanDiskHpVenus[] = {
    { 0x01, "Raw Read Error Rate" },
    { 0x05, "Reassigned Block Count" },
    { 0x09, "Power On Hours" },
    { 0x0C, "Drive Power Cycle Count" },
    { 0xAA, "Reserved Block Count" },
    { 0xAB, "Program Fail Count" },
    { 0xAC, "Erase Fail Count" },
    { 0xAD, "Wear Leveling Count" },
    { 0xAE, "Unexpected Power Loss Count" },
    { 0xB0, "Unused Reserved Block Count" },
    { 0xB7, "SATA Interface Downshift Count" },
    { 0xB8, "End to End Error Detection/Correction Count" },
    { 0xBB, "Uncorrectable Error Count" },
    { 0xBC, "Command Time Out" },
    { 0xBE, "Airflow Temperature" },
    { 0xC2, "Temperature" },
    { 0xC4, "Reallocated Event Count" },
    { 0xC7, "CRC Error Count" },
    { 0xC9, "SSD Life Left" },
    { 0xE6, "Media Wearout Indicator" },
    { 0xF1, "Total LBAs Written" },
    { 0xF2, "Total LBAs Read" },
    { 0xF3, "Total NAND Writes" },
    { 0xF4, "Temperature Throttle Status" },
    { 0xF9, "TLC NAND GB Writes" },
};

static const CdiAttrName kSmartSanDiskDell[] = {
    { 0x05, "Reassigned Block Count" },
    { 0x09, "Power On Hours" },
    { 0x0C, "Drive Power Cycle Count" },
    { 0xAF, "Program Fail Count (Worst Case Component)" },
    { 0xB0, "Erase Fail Count (Worst Case Component)" },
    { 0xB1, "Wear Leveling Count" },
    { 0xB2, "Used Reserved Block Count (Worst Case Component)" },
    { 0xB3, "Used Reserved Block Count (SSD Total)" },
    { 0xB4, "Remaining Reserved Block Count (SSD Total)" },
    { 0xB5, "Program Fail Count (SSD Total)" },
    { 0xB6, "Erase Fail Count (SSD Total)" },
    { 0xBB, "Uncorrectable Error Count" },
    { 0xC2, "Temperature" },
    { 0xC3, "ECC Rate" },
    { 0xC7, "CRC Error Count" },
    { 0xE6, "Media Wearout Indicator" },
    { 0xEE, "Media Wearout Indicator (Cycles Remaining)" },
    { 0xF1, "Total LBAs Written" },
    { 0xF2, "Total LBAs Read" },
};

static const CdiAttrName kSmartSanDiskLenovo[] = {
    { 0x05, "Reassigned Block Count" },
    { 0x09, "Power On Hours" },
    { 0x0C, "Drive Power Cycle Count" },
    { 0xA6, "Minimum P/E Cycles" },
    { 0xA7, "Maximum Bad Blocks per Die" },
    { 0xA8, "Maximum P/E cycles" },
    { 0xA9, "Total Bad Blocks" },
    { 0xAA, "Grown Bad Blocks" },
    { 0xAB, "Program Fail Count" },
    { 0xAC, "Erase Fail Count" },
    { 0xAD, "Average P/E Cycles Attribute" },
    { 0xAE, "Unexpected Power Loss Count" },
    { 0xB2, "Used Reserved Block Count" },
    { 0xB4, "Remaining Reserved Block Count" },
    { 0xB8, "End to End Error Detection/Correction Count" },
    { 0xBB, "UECC Count" },
    { 0xBC, "Command Time Out" },
    { 0xC2, "Temperature" },
    { 0xC7, "SATA CRC Errors" },
    { 0xD4, "SATA PHY Errors" },
    { 0xE6, "Media Wearout Indicator" },
    { 0xE8, "Available Reserved Space" },
    { 0xE9, "NAND GB Written" },
    { 0xEA, "NAND GB Written (SLC)" },
    { 0xF1, "Total Host GB Write" },
    { 0xF2, "Total GB Read" },
    { 0xF3, "Throttle Statistics" },
    { 0xF4, "Thermal Throttle Status" },
};

static const CdiAttrName kSmartSanDiskLenovoHelenVenus[] = {
    { 0x05, "Reassigned Block Count" },
    { 0x09, "Power On Hours" },
    { 0x0C, "Drive Power Cycle Count" },
    { 0xA6, "Minimum P/E Cycles" },
    { 0xA7, "Maximum Bad Blocks per Die" },
    { 0xA8, "Maximum P/E cycles" },
    { 0xA9, "Total Bad Blocks" },
    { 0xAA, "Grown Bad Blocks" },
    { 0xAB, "Program Fail Count" },
    { 0xAC, "Erase Fail Count" },
    { 0xAD, "Average P/E Cycles Attribute" },
    { 0xAE, "Unexpected Power Loss Count" },
    { 0xB2, "Used Reserved Block Count" },
    { 0xB4, "Remaining Reserved Block Count" },
    { 0xB8, "End to End Error Detection/Correction Count" },
    { 0xBB, "UECC Count" },
    { 0xBC, "Command Time Out" },
    { 0xC2, "Temperature" },
    { 0xC7, "SATA CRC Errors" },
    { 0xD4, "SATA PHY Errors" },
    { 0xE8, "Available Reserved Space" },
    { 0xE9, "Media Wearout Indicator" },
    { 0xEA, "NAND GB Written (SLC)" },
    { 0xF1, "Total Host GB Write" },
    { 0xF2, "Total GB Read" },
    { 0xF3, "Throttle Statistics" },
    { 0xF4, "Thermal Throttle Status" },
    { 0xF9, "NAND GB Written (TLC)" },
};

static const CdiAttrName kSmartMicronMU03[] = {
    { 0x01, "Raw Read Error Rate" },
    { 0x05, "Reallocated NAND Block Count" },
    { 0x09, "Power On Hours Count" },
    { 0x0C, "Power Cycle Count" },
    { 0xAB, "Program Fail Count" },
    { 0xAC, "Erase Fail Count" },
    { 0xAD, "Average Block Erase Count" },
    { 0xAE, "Unexpected Power Loss Count" },
    { 0xB4, "Unused Spare NAND Blocks" },
    { 0xB5, "Non-4K Aligned Access" },
    { 0xB7, "SATA interface Downshift" },
    { 0xB8, "Error Correction Count" },
    { 0xBB, "Reported Uncorrectable Errors" },
    { 0xC2, "Temperature" },
    { 0xC4, "Reallocation Event Count" },
    { 0xC5, "Current Pending ECC Count" },
    { 0xC6, "SMART Offline Scan Uncorrectable Error Count" },
    { 0xC7, "UDMA CRC Error Count" },
    { 0xCA, "Lifetime Remaining" },
    { 0xCE, "Write Error Rate" },
    { 0xD2, "Successful RAIN Recovery Count" },
    { 0xF0, "Host Program Page Count" },
    { 0xF1, "Total LBAs Written" },
    { 0xF2, "Total LBAs Read" },
    { 0xF3, "Total Program Page Count" },
    { 0xF6, "Cumulative Host Sectors Written" },
    { 0xF7, "Host Program NAND Pages Count" },
    { 0xF8, "FTL Program NAND Pages Count" },
};

static const CdiAttrName kSmartSanDiskCloud[] = {
    { 0x05, "Retired Block Count" },
    { 0x09, "Power On Hours" },
    { 0x0D, "Count of Uncorrectable ECC Errors" },
    { 0x20, "Write Amplification multiplied by 100" },
    { 0x21, "Write Amplification Factor" },
    { 0xAA, "Reserve Block Count" },
    { 0xAB, "Program Fail Count" },
    { 0xAC, "Erase Fail Count" },
    { 0xAD, "Average Write/Erase Count" },
    { 0xAE, "Unexpected Power Loss Count" },
    { 0xB2, "SSD Life Left (upto 0.01%)" },
    { 0xBF, "Clean Shutdown Count" },
    { 0xC0, "Unclean Shutdown Count" },
    { 0xC2, "Temperature" },
    { 0xC4, "Number of Blocks Reallocated" },
    { 0xE6, "Percent of Total Write/Erase Count" },
    { 0xE8, "Spare Blocks Remaining" },
    { 0xE9, "Total Nand Writes 64GB" },
    { 0xEB, "Capacitor Health" },
    { 0xF1, "Total Host Writes 64GB" },
    { 0xF2, "Total Host Reads 64GB" },
    { 0xF4, "Lifetime Thermal Throttle Activations" },
    { 0xF5, "Percent Drive Life Remaining" },
    { 0xFD, "SPI Tests Remaining" },
};

static const CdiAttrName kSmartSiliconMotionCVC[] = {
    { 0x05, "Re-Assigned Count" },
    { 0x09, "Power-On Hours Count" },
    { 0x0C, "Drive Power Cycle Count" },
    { 0xA5, "SLC Cache" },
    { 0xAA, "Grown Bad Block Count" },
    { 0xAB, "Program Fail Count" },
    { 0xAC, "Erase Fail Count" },
    { 0xAD, "Avg Erase Count" },
    { 0xAE, "Unexpected Power Loss Count" },
    { 0xAF, "Program Fail Count (Worst case)" },
    { 0xB7, "Total SATA Link Speed Downshift" },
    { 0xB8, "End-to-End Data Errors corrected" },
    { 0xBB, "Uncorrectable Errors" },
    { 0xBD, "Max Erase Count" },
    { 0xBE, "Temperature" },
    { 0xBF, "Min Erase Count" },
    { 0xC3, "Read Error Rate" },
    { 0xC6, "Off-Line Scan Uncorrectable Sector Count" },
    { 0xC7, "SATA CRC Error Count" },
    { 0xCA, "SSD Life Left" },
    { 0xE8, "Total Spare Counts" },
    { 0xE9, "TLC NAND Write" },
    { 0xF1, "Host Write" },
    { 0xF2, "Host Read" },
    { 0x94, "RAID Event Count" },
    { 0x95, "RAID Uncorrectable Count" },
    { 0xA7, "SSD Protect Mode" },
    { 0x93, "Soft Retry Event Count" },
    { 0xEA, "SLC NAND Write" },
};

static const CdiAttrName kSmartAdataIndustrial[] = {
    { 0x09, "Power-On hours Count" },
    { 0x0C, "Drive Power Cycle Count" },
    { 0xA7, "SSD Protect Mode" },
    { 0xA8, "SATA PHY Error Count" },
    { 0xA9, "Bad Block Count" },
    { 0xAD, "Erase Count" },
    { 0xAF, "Bad Cluster Table Count" },
    { 0xB4, "Spare block count left" },
    { 0xC0, "Unexpected Power Loss Count" },
    { 0xC2, "Temperature" },
    { 0xE7, "SSD life left" },
    { 0xE9, "Flash Write Sector Count" },
    { 0xEA, "Flash Read Sector Count" },
    { 0xF1, "Write Sector Count" },
    { 0xF2, "Read Sector Count" },
};

static const CdiAttrTable kAttrTables[] = {
    { "Smart", kSmart, 59 },
    { "SmartSsd", kSmartSsd, 21 },
    { "SmartMtron", kSmartMtron, 1 },
    { "SmartIndilinx", kSmartIndilinx, 20 },
    { "SmartJMicron60x", kSmartJMicron60x, 8 },
    { "SmartIntel", kSmartIntel, 29 },
    { "SmartSamsung", kSmartSamsung, 30 },
    { "SmartSandForce", kSmartSandForce, 28 },
    { "SmartJMicron61x", kSmartJMicron61x, 16 },
    { "SmartMicron", kSmartMicron, 46 },
    { "SmartMicronMU02", kSmartMicronMU02, 65 },
    { "SmartOcz", kSmartOcz, 31 },
    { "SmartPlextor", kSmartPlextor, 30 },
    { "SmartSanDisk", kSmartSanDisk, 15 },
    { "SmartOczVector", kSmartOczVector, 35 },
    { "SmartCorsair", kSmartCorsair, 14 },
    { "SmartToshiba", kSmartToshiba, 22 },
    { "SmartSanDiskGb", kSmartSanDiskGb, 30 },
    { "SmartKingston", kSmartKingston, 28 },
    { "SmartNVMe", kSmartNVMe, 29 },
    { "SmartRealtek", kSmartRealtek, 31 },
    { "SmartSKhynix", kSmartSKhynix, 38 },
    { "SmartKioxia", kSmartKioxia, 9 },
    { "SmartWdc", kSmartWdc, 30 },
    { "SmartKingstonSuv", kSmartKingstonSuv, 26 },
    { "SmartKingstonKC600", kSmartKingstonKC600, 30 },
    { "SmartKingstonDC500", kSmartKingstonDC500, 26 },
    { "SmartKingstonSA400", kSmartKingstonSA400, 25 },
    { "SmartSsstc", kSmartSsstc, 30 },
    { "SmartIntelDc", kSmartIntelDc, 27 },
    { "SmartApacer", kSmartApacer, 14 },
    { "SmartSiliconMotion", kSmartSiliconMotion, 37 },
    { "SmartJMicron66x", kSmartJMicron66x, 23 },
    { "SmartPhison", kSmartPhison, 11 },
    { "SmartSeagate", kSmartSeagate, 28 },
    { "SmartSeagateIronWolf", kSmartSeagateIronWolf, 26 },
    { "SmartMarvell", kSmartMarvell, 12 },
    { "SmartMaxiotek", kSmartMaxiotek, 29 },
    { "SmartSeagateBarraCuda", kSmartSeagateBarraCuda, 28 },
    { "SmartYmtc", kSmartYmtc, 30 },
    { "SmartScy", kSmartScy, 23 },
    { "SmartRecadata", kSmartRecadata, 21 },
    { "SmartSanDiskHp", kSmartSanDiskHp, 25 },
    { "SmartSanDiskHpVenus", kSmartSanDiskHpVenus, 25 },
    { "SmartSanDiskDell", kSmartSanDiskDell, 19 },
    { "SmartSanDiskLenovo", kSmartSanDiskLenovo, 28 },
    { "SmartSanDiskLenovoHelenVenus", kSmartSanDiskLenovoHelenVenus, 28 },
    { "SmartMicronMU03", kSmartMicronMU03, 28 },
    { "SmartSanDiskCloud", kSmartSanDiskCloud, 24 },
    { "SmartSiliconMotionCVC", kSmartSiliconMotionCVC, 29 },
    { "SmartAdataIndustrial", kSmartAdataIndustrial, 15 },
};

bool CdiFindAttrTable(const char* key, const CdiAttrName** entries, int* count)
{
    if (!key || !entries || !count) return false;
    for (const auto& t : kAttrTables) {
        if (strcmp(t.key, key) == 0) {
            *entries = t.entries;
            *count = t.count;
            return true;
        }
    }
    return false;
}

} // namespace cdi
